spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springwebapp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=America/New_York
    username: root
    password: root
    hikari:
      # connection pool settings
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 10 # 10 is the default
      auto-commit: true
      idle-timeout: 180000 # 180 seconds, default is 10 minutes
      connection-timeout: 30000
      connection-test-query: SELECT 1 # MySQL heartbeat query
      max-lifetime: 1800000 # connection max lifetime, default is 30 minutes

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml # mapper xml file path
  type-aliases-package: com.example.springwebapp.pojo # mybatis return entity package name

logging: # MyBatis Log config
  level:
    com.webapp.mapper: debug
    com.webapp.service: debug
    com.webapp.controller: debug
    com.webapp.config: debug
    com.webapp.dao: debug
    com.webapp.util: debug
    com.webapp.interceptor: debug
    com.webapp.exception: debug

